package student_aleksandr_zuk.lesson_12.level_3;

class MultiCatchExample {

    public static void main(String[] args) {

        try {

        } catch (Exception e) {

        }
    }
}
//ArithmeticException включён в Exception, он уже будет проверен
// до того как дойдёт до catch (ArithmeticException a)